-- ISNCSCI / Spinal Cord Assessment — full database schema
-- Target: PostgreSQL 15+ (Supabase)
--
-- Usage (Supabase SQL editor or psql):
--   1. Run this file on an empty `public` schema to create all tables.
--   2. If upgrading an existing DB that still has numeric assessment_id,
--      use supabase/migrations/20260521234028_assessment_id_llnn_format.sql instead.
--   3. Optionally run seed.example.sql for dev data.

-- =============================================================================
-- Core: Patient
-- =============================================================================

CREATE TABLE "Patient" (
  patient_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nhi_number character varying NOT NULL,
  date_of_birth date,
  gender character varying,
  nz_citizenship_status character varying,
  place_of_birth character varying,
  date_of_death date,
  created_at date,
  is_active character varying,
  fhir_patient_id character varying,
  ethnicity text
);

CREATE TABLE "Patient Contact" (
  contact_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PATIENTpatient_id" bigint NOT NULL REFERENCES "Patient"(patient_id),
  email_address character varying,
  home_phone_no bigint,
  mobile_phone_co bigint,
  created_at date,
  updated_at date
);

CREATE TABLE "Patient Name" (
  name_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PATIENTpatient_id" bigint NOT NULL REFERENCES "Patient"(patient_id),
  family_name character varying,
  given_name character varying,
  preferred_name character varying,
  prefix character varying,
  suffix character varying,
  created_at date,
  updated_at date
);

CREATE TABLE "Patient Address" (
  address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PATIENTpatient_id" bigint NOT NULL REFERENCES "Patient"(patient_id),
  type character varying,
  line1 character varying,
  line2 character varying,
  city character varying,
  suburb character varying,
  postal_code bigint,
  country character varying,
  created_at date,
  updated_at date
);

CREATE TABLE "GP Enrollment" (
  enrollment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PATIENTpatient_id" bigint NOT NULL REFERENCES "Patient"(patient_id),
  enrollment_reference character varying,
  hpi_practitioner_id character varying,
  hpi_organisation_id character varying,
  hpi_facility_id character varying,
  enrollment_start date,
  enrollment_end date,
  created_at date,
  updated_at date
);

CREATE TABLE "Patient NHI Identifier" (
  nhi_identifier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PATIENTpatient_id" bigint NOT NULL REFERENCES "Patient"(patient_id),
  nhi_number character varying NOT NULL UNIQUE,
  nhi_use character varying,
  assigned_at date,
  linked_at date,
  created_at timestamp without time zone
);

-- =============================================================================
-- Staff & authentication (app login uses Staff Credentials + bcrypt)
-- =============================================================================

CREATE TABLE "Staff" (
  staff_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hpi_practitioner character varying NOT NULL UNIQUE,
  role character varying,
  department character varying,
  is_active character varying,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  email text NOT NULL,
  auth_user_id uuid
);

CREATE TABLE "Staff Name" (
  name_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "STAFFstaff_id" bigint NOT NULL REFERENCES "Staff"(staff_id),
  family_name character varying,
  given_name character varying,
  preferred_name character varying,
  prefix character varying,
  created_at timestamp without time zone,
  updated_at timestamp without time zone
);

CREATE TABLE "Staff Credentials" (
  credential_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "STAFFstaff_id" bigint NOT NULL REFERENCES "Staff"(staff_id),
  username text NOT NULL UNIQUE,
  password_hash character varying,
  last_login timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone
);

-- =============================================================================
-- Assessments (assessment_id = LLNN, e.g. AB12)
-- =============================================================================

CREATE TABLE "Assessment" (
  assessment_id char(4) NOT NULL PRIMARY KEY,
  "PATIENTpatient_id" bigint NOT NULL REFERENCES "Patient"(patient_id),
  "STAFFstaff_id" bigint NOT NULL REFERENCES "Staff"(staff_id),
  assessment_date date,
  status character varying,
  current_version bigint,
  injury_date date,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  review_date date,
  CONSTRAINT assessment_id_llnn_format CHECK (assessment_id ~ '^[A-Z]{2}[0-9]{2}$')
);

CREATE TABLE "Draft Assessment" (
  draft_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ASSESSMENTassessment_id" char(4) NOT NULL REFERENCES "Assessment"(assessment_id),
  "STAFFstaff_id" bigint REFERENCES "Staff"(staff_id),
  is_current_draft character varying,
  notes character varying,
  last_saved_at timestamp without time zone,
  created_at timestamp without time zone
);

CREATE TABLE "Assessment Version" (
  version_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ASSESSMENTassessment_id" char(4) NOT NULL REFERENCES "Assessment"(assessment_id),
  "STAFFstaff_id" bigint NOT NULL REFERENCES "Staff"(staff_id),
  version_number bigint,
  change_reason character varying,
  created_at timestamp without time zone
);

CREATE TABLE "Final Assessment" (
  final_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ASSESSMENTassessment_id" char(4) NOT NULL REFERENCES "Assessment"(assessment_id),
  "STAFFstaff_id" bigint REFERENCES "Staff"(staff_id),
  version_number bigint,
  is_current_final character varying,
  pdf_url character varying,
  notes character varying,
  finalised_at timestamp with time zone,
  created_at timestamp without time zone
);

-- =============================================================================
-- Exam & ISNCSCI scores
-- =============================================================================

CREATE TABLE "Exam" (
  exam_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ASSESSMENTassessment_id" char(4) NOT NULL REFERENCES "Assessment"(assessment_id),
  version_number bigint,
  exam_date date,
  voluntary_anal_contraction character varying,
  deep_anal_pressure character varying,
  comments character varying,
  created_at timestamp without time zone
);

CREATE TABLE "Exam Side" (
  exam_side_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EXAMexam_id" bigint NOT NULL REFERENCES "Exam"(exam_id),
  side character varying,
  lowest_non_key_muscle_w_motor character varying,
  created_at timestamp without time zone
);

CREATE TABLE "Motor Score" (
  motor_score_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EXAM_SIDEexam_side_id" bigint NOT NULL REFERENCES "Exam Side"(exam_side_id),
  spinal_level character varying,
  value character varying,
  created_at timestamp without time zone
);

CREATE TABLE "Light Touch Score" (
  lt_score_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EXAM_SIDEexam_side_id" bigint NOT NULL REFERENCES "Exam Side"(exam_side_id),
  spinal_level character varying,
  value character varying,
  created_at timestamp without time zone
);

CREATE TABLE "Pin Prick Score" (
  pp_score_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EXAM_SIDEexam_side_id" bigint NOT NULL REFERENCES "Exam Side"(exam_side_id),
  spinal_level character varying,
  value character varying,
  created_at timestamp without time zone
);

CREATE TABLE "Classification Result" (
  classification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EXAMexam_id" bigint NOT NULL REFERENCES "Exam"(exam_id),
  nli_sensory_right character varying,
  nli_sensory_left character varying,
  nli_motor_right character varying,
  nli_motor_left character varying,
  neurological_level_of_injury character varying,
  injury_complete character varying,
  als_grade character varying,
  zpp_sensory_right character varying,
  zpp_sensory_left character varying,
  zpp_motor_right character varying,
  zpp_motor_left character varying,
  calculated_at timestamp without time zone
);

CREATE TABLE "Assessment Totals" (
  totals_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EXAMexam_id" bigint NOT NULL REFERENCES "Exam"(exam_id),
  right_upper_extremity character varying,
  right_lower_extremity character varying,
  right_light_touch character varying,
  right_pin_prick character varying,
  right_motor character varying,
  left_upper_extremity character varying,
  left_lower_extremity character varying,
  left_light_touch character varying,
  left_pin_prick character varying,
  left_motor character varying,
  upper_extremity_total character varying,
  lower_extremity_total character varying,
  light_touch_total character varying,
  pin_prick_total character varying,
  calculated_at timestamp without time zone
);

-- =============================================================================
-- Row Level Security (prototype: permissive policies)
-- The Next.js app uses the Supabase anon key without Supabase Auth JWT today,
-- so policies are granted to both `anon` and `authenticated`.
-- Tighten these before production / real patient data.
-- =============================================================================

DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'Patient',
    'Patient Contact',
    'Patient Name',
    'Patient Address',
    'GP Enrollment',
    'Patient NHI Identifier',
    'Staff',
    'Staff Name',
    'Staff Credentials',
    'Assessment',
    'Draft Assessment',
    'Assessment Version',
    'Final Assessment',
    'Exam',
    'Exam Side',
    'Motor Score',
    'Light Touch Score',
    'Pin Prick Score',
    'Classification Result',
    'Assessment Totals'
  ];
BEGIN
  FOREACH t IN ARRAY tables
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);

    EXECUTE format(
      'CREATE POLICY %I ON %I FOR SELECT TO anon, authenticated USING (true)',
      t || ' shared select',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR INSERT TO anon, authenticated WITH CHECK (true)',
      t || ' shared insert',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)',
      t || ' shared update',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR DELETE TO anon, authenticated USING (true)',
      t || ' shared delete',
      t
    );
  END LOOP;
END $$;

-- API roles (Supabase includes these by default; safe to re-run)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
