-- Patient injury record, audit log, phone as text

CREATE TABLE IF NOT EXISTS "Patient Injury" (
  injury_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PATIENTpatient_id" bigint NOT NULL UNIQUE REFERENCES "Patient"(patient_id),
  injury_date date,
  injury_cause character varying,
  notes text,
  review_date date,
  created_at timestamp without time zone,
  updated_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS "Audit Log" (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type character varying NOT NULL,
  entity_id character varying NOT NULL,
  action character varying NOT NULL,
  "STAFFstaff_id" bigint REFERENCES "Staff"(staff_id),
  details jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now()
);

ALTER TABLE "Patient Contact"
  ALTER COLUMN home_phone_no TYPE character varying USING home_phone_no::text,
  ALTER COLUMN mobile_phone_co TYPE character varying USING mobile_phone_co::text;

DO $$
DECLARE
  t text;
  tables text[] := ARRAY['Patient Injury', 'Audit Log'];
BEGIN
  FOREACH t IN ARRAY tables
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON %I',
      t || ' shared select',
      t
    );
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON %I',
      t || ' shared insert',
      t
    );
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON %I',
      t || ' shared update',
      t
    );
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON %I',
      t || ' shared delete',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR SELECT TO anon, authenticated USING (true)',
      t || ' shared select',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR INSERT TO anon, authenticated WITH CHECK (true)',
      t || ' shared insert',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)',
      t || ' shared update',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR DELETE TO anon, authenticated USING (true)',
      t || ' shared delete',
      t
    );
  END LOOP;
END $$;

GRANT ALL ON "Patient Injury" TO anon, authenticated, service_role;
GRANT ALL ON "Audit Log" TO anon, authenticated, service_role;
